/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as ManualIndexRouteImport } from './routes/manual/index'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualIndexRoute = ManualIndexRouteImport.update({
  id: '/manual/',
  path: '/manual/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/manual/': typeof ManualIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/manual': typeof ManualIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/manual/': typeof ManualIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manual/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manual'
  id: '__root__' | '/(home)/' | '/manual/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  ManualIndexRoute: typeof ManualIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/': {
      id: '/manual/'
      path: '/manual'
      fullPath: '/manual/'
      preLoaderRoute: typeof ManualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  ManualIndexRoute: ManualIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
