/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as ManualIndexRouteImport } from './routes/manual/index'
import { Route as SessionIndexRouteImport } from './routes/session/index'
import { Route as RoomRoomCodeIndexRouteImport } from './routes/room/$roomCode/index'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualIndexRoute = ManualIndexRouteImport.update({
  id: '/manual/',
  path: '/manual/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomCodeIndexRoute = RoomRoomCodeIndexRouteImport.update({
  id: '/room/$roomCode/',
  path: '/room/$roomCode/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/manual/': typeof ManualIndexRoute
  '/session/': typeof SessionIndexRoute
  '/room/$roomCode/': typeof RoomRoomCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/manual': typeof ManualIndexRoute
  '/session': typeof SessionIndexRoute
  '/room/$roomCode': typeof RoomRoomCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/manual/': typeof ManualIndexRoute
  '/session/': typeof SessionIndexRoute
  '/room/$roomCode/': typeof RoomRoomCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manual/' | '/session/' | '/room/$roomCode/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manual' | '/session' | '/room/$roomCode'
  id: '__root__' | '/(home)/' | '/manual/' | '/session/' | '/room/$roomCode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  ManualIndexRoute: typeof ManualIndexRoute
  SessionIndexRoute: typeof SessionIndexRoute
  RoomRoomCodeIndexRoute: typeof RoomRoomCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/': {
      id: '/manual/'
      path: '/manual'
      fullPath: '/manual/'
      preLoaderRoute: typeof ManualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/session'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomCode/': {
      id: '/room/$roomCode/'
      path: '/room/$roomCode'
      fullPath: '/room/$roomCode/'
      preLoaderRoute: typeof RoomRoomCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  ManualIndexRoute: ManualIndexRoute,
  SessionIndexRoute: SessionIndexRoute,
  RoomRoomCodeIndexRoute: RoomRoomCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
